### ISSUE TITLE
Deutsch oder Englisch?

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#1]
Auf der Startseite findet man einen Mix aus Deutsch und Englisch. Hier solltet ihr euch einig werden. :-)

Siehe Screenshot.

Ist geplant, mehrere Sprachen anzubieten?

<img width="551" alt="Bildschirmfoto 2024-10-27 um 12 00 32" src="https://github.com/user-attachments/assets/45011e2e-543c-4f72-a012-eebf6030f41f">

**Comment by Tammi23** [comment]
Nein, es ist aktuell nur Deutsch geplant.

**Comment by EdwinEvil** [comment]
ist geändert (nur Login möchte ich englisch lassen, da es überall bekannt ist und in meinen Augen besser wirkt als "Anmeldung")

**Comment by EdwinEvil** [comment]
du hast ja recht... Habs übernommen  ;)

**Comment by matthesdr** [comment]
> du hast ja recht... Habs übernommen ;)

Ich weiß ;-)

**Comment by matthesdr** [comment]
Nur um sicher zu gehen, im Header müsste es "LIP2 Anmeldung" heißen und auf dem Button "Anmelden"

Oder man überlegt sich eine ganz andere Headline :-)

**Comment by EdwinEvil** [comment]
genau so hab ich es umgeschrieben. hab für lip2 jetzt auch das logo eingesetzt
