### ISSUE TITLE
Betriebsraum-Dashboard: Konfiguration wird nicht übernommen

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#12]
Wenn ich das Betriebsraum-Dashboard aufrufe, wird für die config des Dashboard auf das Profil verwiesen. Die im Profil gemachten Einstellungen wirken sich aber nicht auf das Betriebsraum-Dashboard aus. Es wird weiterhin auf das Profil verwiesen, um das Dashboard zu konfigurieren.

**Comment by EdwinEvil** [comment]
klingt nach einem Fehler in der DB. Gerade getestet und es klappt
