### ISSUE TITLE
Orga: Fahrzeuginfos stehen nicht sauber untereinander

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#13]
Im Bereich "Orga" stehen die Fahrzeuginfos nicht sauber untereinander. Siehe Screenshot.

<img width="330" alt="Bildschirmfoto 2024-10-28 um 14 31 58" src="https://github.com/user-attachments/assets/68da4be1-d63a-43ab-a196-b6d9558c9abe">

**Comment by EdwinEvil** [comment]
gefixt
