### ISSUE TITLE
Orga/BA verlängern: Die Eingabe negativer Werte ist möglich

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#14]
Im Bereich "Orga" kann für die befristete Außerdienststellung ein negativer Wert eingegeben und scheinbar auch gespeichert werden. Es erscheint jedenfalls keine Fehlermeldung.

<img width="1094" alt="Bildschirmfoto 2024-10-28 um 14 35 48" src="https://github.com/user-attachments/assets/3d912b5f-98fe-4fd4-94db-d1165215bcac">

Lösungsvorschlag: Fachlich scheint die Eingabe von negativen Werten keinen Sinn zu ergeben. Die Möglichkeit der Angabe sollte daher auf natürliche Zahlen begrenzt werden.

Netter Nebeneffekt:
<img width="407" alt="Bildschirmfoto 2024-10-28 um 14 47 58" src="https://github.com/user-attachments/assets/e99bf9e1-42e8-49a6-96d0-35ca65457c6d">

Sowas würde dann auch nicht mehr möglich sein und ich muss kein Issue für die schlechte Fehlermeldung aufmachen. ;-)

**Comment by EdwinEvil** [comment]
gefixt
