### ISSUE TITLE
Orga/BA: Text geht auf Hintergrund ziemlich unter

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#15]
Der Screenshot zeigt den Text "Keine Daten vorhanden". Dieser Text geht auf dem Hintergrund ziemlich unter und ist nicht gut zu lesen.

<img width="434" alt="Bildschirmfoto 2024-10-28 um 14 51 14" src="https://github.com/user-attachments/assets/ecb4c223-e318-438c-995d-7b6a6f17e6e6">

**Comment by EdwinEvil** [comment]
gefixt
