### ISSUE TITLE
Orga/Neue BA erstellen: Schreibweise "Fahrzeug-Typ"

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#16]
Wie im Screenshot zu sehen, ist "Typ" vollständig groß geschrieben. Ich gehe davon aus, dass das nicht so sein muss. :-)

Aktueller Text: "Fahrzeug-TYP"
Erwarteter Text: "Fahrzeug-Typ"

<img width="424" alt="Bildschirmfoto 2024-10-28 um 14 57 38" src="https://github.com/user-attachments/assets/b97beaba-2abe-4e70-bfa4-864593c24c11">

**Comment by EdwinEvil** [comment]
gefixt
