### ISSUE TITLE
Orga/Neue BA: Wechsel zwischen "Du" und "Sie"

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#17]
Siehe Screenshot:

<img width="456" alt="Bildschirmfoto 2024-10-28 um 15 01 28" src="https://github.com/user-attachments/assets/db3567b1-66b3-4c0d-bf69-3bfed37d7d8d">

<img width="459" alt="Bildschirmfoto 2024-10-28 um 15 10 54" src="https://github.com/user-attachments/assets/7132260f-5802-475e-b0af-8c55acd8806f">

<img width="468" alt="Bildschirmfoto 2024-10-28 um 15 31 10" src="https://github.com/user-attachments/assets/e24a784c-94e7-4a4a-8c1b-036d2e0099d9">

Das wäre mal generell eine Überprüfung wert. Es gibt noch weitere Stellen wo die "Sie-Form" genutzt wird. Das sollte einheitlich sein.

**Comment by EdwinEvil** [comment]
gefixt
