### ISSUE TITLE
Startseite: Doppelte Informationen

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#2]
Auf der Startseite findet man jeweils 2 mal "Username" und "Passwort". Ich würde mich hier auf je 1 mal beschränken. Entweder als Label an der Textbox oder als Platzhalter in dem Textfeld. Aber nicht beides. :-)

Wenn Label an der Textbox, dann vielleicht in dem Textfeld ein Beispiel als Platzhalter. Der aktuelle Grauton wäre mir dafür auch noch zu stark. Gerne etwas abschwächen

Wenn ohne Label an Textbox, dann einfach "Username" und "Password" ohne "@" in die Textbox.

<img width="406" alt="Bildschirmfoto 2024-10-27 um 12 10 24" src="https://github.com/user-attachments/assets/8b2372ce-5262-45fe-b15d-8bfaf5623329">

**Comment by EdwinEvil** [comment]
ist geändert
