### ISSUE TITLE
Wöchentliche Desi/Planungsübersicht und Verwaltung: Leerzeichen

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#20]
Bitte die im Screenshot markierten Leerzeichen entfernen. Die gehören da nicht hin. :-)

<img width="782" alt="Bildschirmfoto 2024-10-28 um 15 27 06" src="https://github.com/user-attachments/assets/63441909-bb43-476f-98a3-4db948b874fa">

**Comment by EdwinEvil** [comment]
gefixt
