### ISSUE TITLE
Wöchentliche Desi/Planungsübersicht und Verwaltung: Neuen Zeitplan erstellen

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#21]
Ich bin ja nicht vom Fach aber wenn ich eine Combobox öffne, wo das Label "Sachgebiet" dran steht, erwarte ich nicht die Auswahl von Wochentagen. Ist das fachlich korrekt? Kann mir das jemand erklären?

<img width="478" alt="Bildschirmfoto 2024-10-28 um 15 32 04" src="https://github.com/user-attachments/assets/477e9c0b-4a1f-4a23-a820-d338d2f5476a">

**Comment by EdwinEvil** [comment]
schon länger lokal gefixt ;) komt mit dem nächsten update der online-version
