### ISSUE TITLE
Favicon Drafts

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#23]
Ich schmeiß hier einfach mal rein, was mir für das Logo in den Sinn kommt

![Logo_lip2_draft1](https://github.com/user-attachments/assets/aa681bc4-64e7-4a45-8306-97d55ad51d4d)
![Logo_lip2](https://github.com/user-attachments/assets/01a7694e-450d-43e7-84a7-9421d8e69be1)

**Comment by EdwinEvil** [comment]
super! Danke für die Vorlagen :)

**Comment by Tammi23** [comment]
Haben - bis zum professionell Erstellen lassen - erstmal eine einfache Alternative.
