### ISSUE TITLE
Typo in Text

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#24]
Der Screenshot zeigt einen typo in dem beschreibenen Text.

<img width="527" alt="Bildschirmfoto 2024-11-01 um 13 14 34" src="https://github.com/user-attachments/assets/488b2162-8f77-456c-8d82-404ba1e5d366">

<img width="518" alt="Bildschirmfoto 2024-11-01 um 13 18 11" src="https://github.com/user-attachments/assets/533a9206-981f-4153-abcc-f374b7b004cf">

<img width="301" alt="Bildschirmfoto 2024-11-01 um 13 21 37" src="https://github.com/user-attachments/assets/e04d620b-9348-4345-b184-6054944db63d">

**Comment by EdwinEvil** [comment]
gefixt
