### ISSUE TITLE
Rettungsdienst: Wording beibehalten

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#25]
Im Bereich "Rettungsdienst" kann man über den Button "+ Notiz" eine neue Notiz hinzufügen. In den darauf folgenden Dialogen wird aber von "Einträgen" gesprochen. Hier sollte man meiner Meinung nach ein einheitliches wording nutzen. Wenn der Button "+ Notiz" heißt, sollte der sich öffnende Dialog auch den Titel "Neue Notiz" haben. Auch der Bestätigungsdialog nach dem Speichern sagt "Eintrag erstellt". Auch hier sollte das worin konsequent fortgesetzt werden: "Notiz erstellt"

<img width="1348" alt="Bildschirmfoto 2024-11-01 um 13 24 56" src="https://github.com/user-attachments/assets/d4c8dea3-8b23-4ed4-ac3c-4a3adf7e4b16">

<img width="420" alt="Bildschirmfoto 2024-11-01 um 13 26 34" src="https://github.com/user-attachments/assets/f7a78c64-4e1e-4e84-8903-10e0993fa08f">

**Comment by EdwinEvil** [comment]
gefixt
