### ISSUE TITLE
Notizblock: Anzahl der Zeichen für eine neue Notiz

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#26]
Ich habe festgestellt, dass es für die Notiz scheinbar keine Begrenzung für die Anzahl der Zeichen gibt. Für den Anwender sicherlich top, für die DB im Hintergrund möglicherweise irgendwann problematisch. Denkt mal drüber nach, ob ihr da ein Limit setzen wollt. Solltet ihr euch dafür entscheiden, empfehle ich unter der Textbox einen Zeichen-Counter der die Anzahl der vorhandenen Zeichen und die maximal möglichen Zeichen anzeigt: `"("$(current_letters)"/"$(max_letters)")"` <-- Keine Garantie auf korrekte Syntax ;-)

**Comment by EdwinEvil** [comment]
gute idee und eingebaut :)
