### ISSUE TITLE
Technik/Aktuelle Tickets: Schreibweise der möglichen Ticketstatus nicht einheitlich

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#32]
Siehe Screenshot:

<img width="423" alt="Bildschirmfoto 2024-11-01 um 14 17 06" src="https://github.com/user-attachments/assets/e4c16af6-cb76-4a49-83b1-46eac522462c">

**Comment by Tammi23** [comment]
Die ersten drei Status sind vorgegeben. Alle weiteren sind frei Eintrag bar über die Admin-UI. Das heißt "unsere" 3 sind Einheitlich und etwas hervorgehoben. Alle anderen sind selber zu gestalten.
