### ISSUE TITLE
Technik/Technik intern: Fehler beim Speichern "Neuer Wartungstermin"

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#38]
Wenn man versucht einen neuen Wartungstermin zu speichern, kommt es zu einem Fehler. Siehe Screenshot. Der neue Wartungstermin kann daher nicht gespeichert werden. 

Der Text in der Fehlermeldung enthält ebenfalls Fehler. Die Lösung steht im Screenshot.

<img width="856" alt="Bildschirmfoto 2024-11-01 um 14 35 51" src="https://github.com/user-attachments/assets/1d27951d-d269-48a4-a7e3-13c4e867fab2">

**Comment by leitnetmain** [comment]
Fehler bei der Datenbankoperation: invalid input syntax for type integer: "Wurstblinker"
2024-11-01T13:43:28.614Z [ERROR]: Fehler bei der Datenbankoperation: invalid input syntax for type integer: "Wurstblinker"
2024-11-01T13:46:21.368Z [ERROR]: Fehler bei der Datenbankoperation: invalid input syntax for type integer: "Wurstblinker"

@EdwinEvil Hier musst du die Liste mit den Usern laden die Ansprechpartner sein können. 
Wir hatten besprochen, dass hier immer Interne Ansprechpartner sein sollen oder wir eine extra Liste mit "externen" mit Kontakt einpflegen/erstellen müssen. 
Also, gewohnten Picker einbauen.
Für interne einfach die vorhandene API nehmen. Sollten wir uns für Variante 2 entscheiden (maybe auch für Leute mit externer IT interresant), dann muss ich die Tabelle noch erstellen + API. Aber das müssten wir dann auch schon direkt (vorher) im Admin mit verdraht. 
Währe in meinen Augen unter Userverwaltung oder mit extra Punkt Userverwaltung (extern) gut aufgehoben.
Würde dazu aber dann ein Feature-Request schreiben.

**Comment by Tammi23** [comment]
Es stehen erstmal nur interne User zur Auswahl. Style muss noch angepasst werden @EdwinEvil siehe: https://github.com/leitnetmain/nextJS/issues/94
