### ISSUE TITLE
Startseite nach dem Login: Formulierung in Kachel weicht von den anderen ab

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#5]
<img width="1594" alt="Bildschirmfoto 2024-10-27 um 12 27 53" src="https://github.com/user-attachments/assets/c468baf8-a202-482a-b648-38ed786cde0a">

Die Texte in den Kacheln fangen alle mit "Hier ..." an, nur die Kachel für "Profil" nicht. Das wirkt irgendwie fremd, wenn man die anderen Kacheln gelesen hat.

**Comment by EdwinEvil** [comment]
geändert
