### ISSUE TITLE
Profil: Upload eines Profilbildes

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#6]
Der Upload eines Profilbilds funktioniert nicht richtig.

STR:

1. Öffne "Profil"
2. Klicke im Bereich "Profilbild" auf "Neues Bild hochladen"
3. Nutze in dem Dialog den File-Selector zur Auswahl eines Bildes
4. Klicke auf "Speichern"

Actual behaviour:
1. Der Dialog schließt sich nicht. In der Konsole ist zu sehen, dass ein POST https://leitnet.com/api/upload abgesetzt wird. Dieser wird auch mit einem Code 200 quittiert.
2. Wenn man den Dialog mit "Abbrechen" schließt und eine Page-Refresh durchführt, wird im Bereich "Profilbild" die Möglichkeit geboten das vorhandene Bild zu löschen. Angezeigt wird aber kein Bild

Expected behaviour:

1. Nach Auswahl des Bildes sollte der Dialog nach Klicken auf "Speichern" geschlossen werden. Das hochgeladene Profilbild sollte direkt im Profil sichtbar sein

**Comment by Tammi23** [comment]
Ahhh, sehr guter Hinweis! 
Lokal funktioniert das bei uns, aber nicht in der "online"-Version.

**Comment by matthesdr** [comment]
Ich würde noch Infos zu zugelassenen Dateitypen ergänzen. Wenn es eine Limitierung für die Größe gibt, bitte auch diese noch ergänzen

**Comment by Tammi23** [comment]
Fixed with latest commit.
Jetzt auch mit verschlüsseltem Up- und Download
