### ISSUE TITLE
Profil: Labels persönlicher Informationen uneindeutig

### ISSUE THREAD

**Issue by matthesdr** [leitnetmain/lip2issues#7]
<img width="526" alt="Bildschirmfoto 2024-10-27 um 12 45 05" src="https://github.com/user-attachments/assets/654a77dc-cb30-484e-ba8a-0a68d5dde603">

Mein Vorschlag 1:

Vorname:
Nachname:
Benutzername:
Wachabteilung:
Rolle:

Mein Vorschlag 2:

Vorname:
Name:
Benutzername:
Wachabteilung:
Rolle:

Begründung: "Name" und "Nachname" werden oft für das gleiche genutzt. Beides steht für den Nachnamen

**Comment by EdwinEvil** [comment]
ist geändert
